// <auto-generated />
using LeoShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeoShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20230404030818_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LeoShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            CategoryName = "T-shirt",
                            Description = "Mussum Ipsum, cacilds vidis litro abertis.",
                            ImageURL = "https://github.com/leandro-SI/microservices-dotNet6/blob/main/LeoShopping.ProductAPI/Imagens/6_spacex.jpg?raw=true",
                            Name = "Camiseta Spacex",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "T-shirt",
                            Description = "Mussum Ipsum, cacilds vidis litro abertis.",
                            ImageURL = "https://github.com/leandro-SI/microservices-dotNet6/blob/main/LeoShopping.ProductAPI/Imagens/12_gnu_linux.jpg?raw=true",
                            Name = "Camiseta GNU Linux",
                            Price = 70.5m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "T-shirt",
                            Description = "Mussum Ipsum, cacilds vidis litro abertis.",
                            ImageURL = "https://github.com/leandro-SI/microservices-dotNet6/blob/main/LeoShopping.ProductAPI/Imagens/7_coffee.jpg?raw=true",
                            Name = "Camiseta Coffee",
                            Price = 39.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
